### ISSUE TITLE
[UPDATE] Pouvoir modifier les informations basique d'un compte OMNIAUTH

### ISSUE THREAD

**Issue by abarriel** [abarriel/Hypertube#11]
Ouvrir le droit de modifier des informations basique ( sauf login, password ) au compte OMNIAUTH.
Necessaire?

**Comment by Lcharvol** [comment]
Pour moi c'est pas nécessaire de le faire. Apres a voir, si c'est faisable, pourquoi pas.

**Comment by abarriel** [comment]
@dpilarsk  tu en penses quoi?

**Comment by dpilarsk** [comment]
En soit, si tout les compte OmniAuth ont un email, je ne penses pas qu'il y ai la nécessité de leur proposer de changer
