### ISSUE TITLE
[SQL]Mettre la column email dans la table users en clé unique

### ISSUE THREAD

**Issue by dpilarsk** [abarriel/Hypertube#12]
Quand un utilisateur change ses infos de profil, il peut mettre un email appartenant à un utilisateur omniauth

**Comment by abarriel** [comment]
Oui c’est vrai. Pour la petite histoire c’etait Login qui était unique. Et le recover password utiliser le login.. Aussi check le recovery password avec un e-mail d’un compte omniauth  ( sûrement queries/users.ts le getbyemail restraints les email des comptes local uniquement)
