### ISSUE TITLE
Register Field Error problem

### ISSUE THREAD

**Issue by Lcharvol** [abarriel/Hypertube#7]
Erreur sur la page register: Quand on rempli un premiere fois le formulaire avec des champs vide et puis que l'on click sur sign up, on ne pourra plus valider le formulaire car l'erreur 'Veuillez remplir tout les champs' persiste.

Je pense qu'il faut reset les errors sur le sign up puis re-checker tout les champs.

**Comment by dpilarsk** [comment]
Cela est encore le cas même après ma PR ? #6

**Comment by abarriel** [comment]
Oui C'est fix avec ta PR, j'ai bien check.
@Lcharvol   tu as oublié d'ajouter la photo de profile qui est obligatoire
je te laisse close.

**Comment by Lcharvol** [comment]
On peut close du coup?
